-- User-authored free text about their own fit/proportion preferences
-- (e.g. "I prefer higher necklines", "I dress for a pear shape and like
-- structure on top"). Never inferred or generated by the AI — only ever
-- written by the user themselves in Edit Profile — which is what makes it
-- safe to feed into stylist reasoning without violating the no-body-
-- observation rule: the AI is quoting what the user told it, not claiming
-- to have observed anything.
alter table public.profiles add column if not exists styling_notes text;
